development:
  adapter: postgresql
  encoding: unicode
  database: lineup
  pool: 2
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database:
  pool: 2
  username:
  password:
